stages:
   - build
variables:
   TAG: $CI_COMMIT_SHORT_SHA

build-job:
  stage : build
  image : docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: "" 
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - sed -i "s/REPLACE_TAG/$TAG/g" docker-compose.yml
    - docker compose build
    - docker compose push
  

    
