version: "3.8"
services:
  frontend:
    build:
       context: .
       dockerfile: frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend1
      - backend2
    ports:
      - "80:80"

  backend1:
    build: ./backend1
    container_name: backend1
  backend2:
    build: ./backend2
    container_name: backend2

