version: "3.8"
services:
  frontend:
    build:
       context: .
       dockerfile: frontend/Dockerfile
    container_name: frontend
    image: chedli01/frontend-work-v4:REPLACE_TAG
    depends_on:
      - backend1
      - backend2
    ports:
      - "80:80"

  backend1:
    build: ./backend1
    container_name: backend1
    image: chedli01/backend1-work-v4:REPLACE_TAG

  backend2:
    build: ./backend2
    container_name: backend2
    image: chedli01/backend2-work-v4:REPLACE_TAG


